# -*- coding: utf-8 -*-
"""StreamLit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MXth56CC1HyoRwdBjxlX6NzzYgMuXn_2
"""

try:
  import streamlit as st
except ModuleNotFoundError:
  import os
  os.system("pip install streamlit")
  import streamlit as st

import pandas as pd
import plotly.express as px

df= pd.read_csv('Advertising_F.csv')
df.head()

#Show Admin stuff
st.title("Advertising Effectiveness Dashboard_Nahisha_Ashraf") #making a titles for the dashboard
st.sidebar.header("Filters") #it has a header called filters
x_var = st.sidebar.selectbox("X-Axis",['TV', 'radio', 'newspaper']) #x-axis
y_var = st.sidebar.selectbox("Y-Axis", ['sales']) #y-axis
#show scatter plot
fig = px.scatter(df, x=x_var, y=y_var, trendline= 'ols') #ols means ordinarly squares
st.plotly_chart(fig)
#show the data frame
st.write('### Data Frame')
st.dataframe(df)

#lets show map
st.title("I am the map!")
fig = px.scatter_mapbox(df, lat= 'latitude', lon='longitude', color='sales', size= 'TV', hover_name='City')
fig.update_layout(mapbox_style="carto-positron") #make it zoom in and out like google maps
st.plotly_chart(fig) #turn it into a streamlit object
